export const MODULE_NAME = 'materials';

//ACTIONS
export const ACTION_SET_MATERIALS = 'SET_MATERIALS';
export const ACTION_SET_MATERIAL_STOCKS = 'ACTION_SET_MATERIAL_STOCKS';

//MUTATIONS
export const MUTATION_SET_MATERIALS = 'MUTATION_SET_MATERIALS'
export const MUTATION_SET_SEARCH = 'MUTATION_SET_SEARCH'
export const MUTATION_CLEAR_MATERIALS = 'MUTATION_CLEAR_MATERIALS'
export const MUTATION_SET_SHOW_FILTER = 'MUTATION_SET_SHOW_FILTER'
export const MUTATION_TOGGLE_SHOW_FILTER = 'MUTATION_TOGGLE_SHOW_FILTER'
export const MUTATION_SET_PAGE = 'MUTATION_SET_PAGE'
export const MUTATION_SET_MATERIAL = 'MUTATION_SET_MATERIAL'
export const MUTATION_SET_YEARS = 'MUTATION_SET_YEARS'
export const MUTATION_SET_REPORT_YEAR = 'MUTATION_SET_REPORT_YEAR'
export const MUTATION_SET_MATERIAL_STOCKS = 'MUTATION_SET_MATERIAL_STOCKS'
export const MUTATION_SET_MATERIAL_STOCK_PAGE = 'MUTATION_SET_MATERIAL_STOCK_PAGE'

export default {
  MODULE_NAME,
  
  ACTION_SET_MATERIALS,
  ACTION_SET_MATERIAL_STOCKS,

  MUTATION_SET_MATERIALS,
  MUTATION_SET_SEARCH,
  MUTATION_CLEAR_MATERIALS,
  MUTATION_SET_SHOW_FILTER,
  MUTATION_TOGGLE_SHOW_FILTER,
  MUTATION_SET_PAGE,
  MUTATION_SET_MATERIAL,
  MUTATION_SET_YEARS,
  MUTATION_SET_REPORT_YEAR,
  MUTATION_SET_MATERIAL_STOCKS,
  MUTATION_SET_MATERIAL_STOCK_PAGE
}