export const MODULE_NAME = 'materials';

//ACTIONS
export const ACTION_SET_MATERIALS = 'SET_MATERIALS';

//MUTATIONS
export const MUTATION_SET_MATERIALS = 'MUTATION_SET_MATERIALS'
export const MUTATION_SET_SEARCH = 'MUTATION_SET_SEARCH'
export const MUTATION_CLEAR_MATERIALS = 'MUTATION_CLEAR_MATERIALS'

export default {
    MODULE_NAME,
    ACTION_SET_MATERIALS,
    MUTATION_SET_MATERIALS,
    MUTATION_SET_SEARCH,
    MUTATION_CLEAR_MATERIALS
}