import app from './modules/app/constants'
import products from './modules/products/constants'
import materials from './modules/materials/constants'
import combos from './modules/combos/constants'
import clients from './modules/clients/constants'
import address from './modules/address/constants'
import agenda from './modules/agenda/constants'

// APP
export const APP_SET_LOADING = `${app.MODULE_NAME}/${app.MUTATION_SET_LOADING}`;
export const APP_SET_DRAWER = `${app.MODULE_NAME}/${app.MUTATION_SET_DRAWER}`;
export const APP_SET_IMAGE = `${app.MODULE_NAME}/${app.MUTATION_SET_IMAGE}`;
export const APP_SET_COLOR = `${app.MODULE_NAME}/${app.MUTATION_SET_COLOR}`;
export const APP_TOGGLE_DRAWER = `${app.MODULE_NAME}/${app.MUTATION_TOGGLE_DRAWER}`;
export const APP_SET_TOASTR = `${app.MODULE_NAME}/${app.MUTATION_SET_TOASTR}`;
export const APP_SET_PROGRESS_BAR = `${app.MODULE_NAME}/${app.MUTATION_SET_PROGRESS_BAR}`;
export const APP_TOGGLE_PROGRESS_BAR = `${app.MODULE_NAME}/${app.MUTATION_TOGGLE_PROGRESS_BAR}`;
export const APP_SET_NO_CONNECTION = `${app.MODULE_NAME}/${app.MUTATION_SET_NO_CONNECTION}`;

// PRODUCTS
export const PRODUCTS_SET_PRODUCTS = `${products.MODULE_NAME}/${products.MUTATION_SET_PRODUCTS}`;
export const PRODUCTS_SET_SEARCH = `${products.MODULE_NAME}/${products.MUTATION_SET_SEARCH}`;
export const PRODUCTS_SET_SHOW_FILTER = `${products.MODULE_NAME}/${products.MUTATION_SET_SHOW_FILTER}`;
export const PRODUCTS_TOGGLE_SHOW_FILTER = `${products.MODULE_NAME}/${products.MUTATION_TOGGLE_SHOW_FILTER}`;
export const PRODUCTS_SET_PRODUCT = `${products.MODULE_NAME}/${products.MUTATION_SET_PRODUCT}`;
export const PRODUCTS_SET_IMAGES = `${products.MODULE_NAME}/${products.MUTATION_SET_IMAGES}`;
export const PRODUCTS_SET_SEARCH_IMAGES = `${products.MODULE_NAME}/${products.MUTATION_SET_SEARCH_IMAGES}`;
export const PRODUCTS_SET_COMBOS = `${products.MODULE_NAME}/${products.MUTATION_SET_COMBOS}`;
export const PRODUCTS_SET_MATERIALS = `${products.MODULE_NAME}/${products.MUTATION_SET_MATERIALS}`;
export const PRODUCTS_SET_SEARCH_MATERIALS = `${products.MODULE_NAME}/${products.MUTATION_SET_SEARCH_MATERIALS}`;
export const PRODUCTS_SET_YEARS = `${products.MODULE_NAME}/${products.MUTATION_SET_SCHEDULE_YEARS}`;
export const PRODUCTS_SET_REPORT_SCHEDULE_FINISHED_YEAR = `${products.MODULE_NAME}/${products.MUTATION_SET_REPORT_SCHEDULE_FINISHED_YEAR}`;
export const PRODUCTS_SET_REPORT_SCHEDULE_CANCELED_YEAR = `${products.MODULE_NAME}/${products.MUTATION_SET_REPORT_SCHEDULE_CANCELED_YEAR}`;

// MATERIALS
export const MATERIALS_SET_MATERIALS = `${materials.MODULE_NAME}/${materials.MUTATION_SET_MATERIALS}`;
export const MATERIALS_SET_SEARCH = `${materials.MODULE_NAME}/${materials.MUTATION_SET_SEARCH}`;
export const MATERIALS_SET_SHOW_FILTER = `${materials.MODULE_NAME}/${materials.MUTATION_SET_SHOW_FILTER}`;
export const MATERIALS_TOGGLE_SHOW_FILTER = `${materials.MODULE_NAME}/${materials.MUTATION_TOGGLE_SHOW_FILTER}`;
export const MATERIALS_SET_MATERIAL = `${materials.MODULE_NAME}/${materials.MUTATION_SET_MATERIAL}`;
export const MATERIALS_SET_YEARS = `${materials.MODULE_NAME}/${materials.MUTATION_SET_YEARS}`;
export const MATERIALS_SET_REPORT_REGISTER_YEAR = `${materials.MODULE_NAME}/${materials.MUTATION_SET_REPORT_REGISTER_YEAR}`;
export const MATERIALS_SET_REPORT_REMOVE_YEAR = `${materials.MODULE_NAME}/${materials.MUTATION_SET_REPORT_REMOVE_YEAR}`;

// COMBOS
export const COMBOS_SET_COMBOS = `${combos.MODULE_NAME}/${combos.MUTATION_SET_COMBOS}`;
export const COMBOS_SET_SEARCH = `${combos.MODULE_NAME}/${combos.MUTATION_SET_SEARCH}`;
export const COMBOS_SET_SHOW_FILTER = `${combos.MODULE_NAME}/${combos.MUTATION_SET_SHOW_FILTER}`;
export const COMBOS_TOGGLE_SHOW_FILTER = `${combos.MODULE_NAME}/${combos.MUTATION_TOGGLE_SHOW_FILTER}`;
export const COMBOS_SET_COMBO = `${combos.MODULE_NAME}/${combos.MUTATION_SET_COMBO}`;
export const COMBOS_SET_IMAGES = `${combos.MODULE_NAME}/${combos.MUTATION_SET_IMAGES}`;
export const COMBOS_SET_SEARCH_IMAGES = `${combos.MODULE_NAME}/${combos.MUTATION_SET_SEARCH_IMAGES}`;
export const COMBOS_SET_PRODUCTS = `${combos.MODULE_NAME}/${combos.MUTATION_SET_PRODUCTS}`;
export const COMBOS_SET_SEARCH_PRODUCTS = `${combos.MODULE_NAME}/${combos.MUTATION_SET_SEARCH_PRODUCTS}`;

// CLIENTS
export const CLIENTS_SET_CLIENTS = `${clients.MODULE_NAME}/${clients.MUTATION_SET_CLIENTS}`;
export const CLIENTS_SET_SEARCH = `${clients.MODULE_NAME}/${clients.MUTATION_SET_SEARCH}`;
export const CLIENTS_SET_SHOW_FILTER = `${clients.MODULE_NAME}/${clients.MUTATION_SET_SHOW_FILTER}`;
export const CLIENTS_TOGGLE_SHOW_FILTER = `${clients.MODULE_NAME}/${clients.MUTATION_TOGGLE_SHOW_FILTER}`;
export const CLIENTS_SET_CLIENT = `${clients.MODULE_NAME}/${clients.MUTATION_SET_CLIENT}`;

// ADDRESS
export const ADDRESS_SET_CITIES = `${address.MODULE_NAME}/${address.MUTATION_SET_CITIES}`;
export const ADDRESS_SET_COUNTRIES = `${address.MODULE_NAME}/${address.MUTATION_SET_COUNTRIES}`;

// AGENDA
export const AGENDA_SET_AGENDA = `${agenda.MODULE_NAME}/${agenda.MUTATION_SET_AGENDA}`;
export const AGENDA_SET_SEARCH = `${agenda.MODULE_NAME}/${agenda.MUTATION_SET_SEARCH}`;
export const AGENDA_SET_SHOW_FILTER = `${agenda.MODULE_NAME}/${agenda.MUTATION_SET_SHOW_FILTER}`;
export const AGENDA_TOGGLE_SHOW_FILTER = `${agenda.MODULE_NAME}/${agenda.MUTATION_TOGGLE_SHOW_FILTER}`;
export const AGENDA_SET_SCHEDULE = `${agenda.MODULE_NAME}/${agenda.MUTATION_SET_SCHEDULE}`;
export const AGENDA_SET_MATERIALS = `${agenda.MODULE_NAME}/${agenda.MUTATION_SET_MATERIALS}`;
export const AGENDA_SET_PRODUCTS = `${agenda.MODULE_NAME}/${agenda.MUTATION_SET_PRODUCTS}`;
export const AGENDA_SET_COMBOS = `${agenda.MODULE_NAME}/${agenda.MUTATION_SET_COMBOS}`;

export default {
  APP_SET_LOADING,
  APP_SET_DRAWER,
  APP_SET_IMAGE,
  APP_SET_COLOR,
  APP_TOGGLE_DRAWER,
  APP_SET_TOASTR,
  APP_SET_PROGRESS_BAR,
  APP_TOGGLE_PROGRESS_BAR,
  APP_SET_NO_CONNECTION,

  PRODUCTS_SET_PRODUCTS,
  PRODUCTS_SET_SEARCH,
  PRODUCTS_SET_SHOW_FILTER,
  PRODUCTS_TOGGLE_SHOW_FILTER,
  PRODUCTS_SET_PRODUCT,
  PRODUCTS_SET_IMAGES,
  PRODUCTS_SET_SEARCH_IMAGES,
  PRODUCTS_SET_COMBOS,
  PRODUCTS_SET_MATERIALS,
  PRODUCTS_SET_SEARCH_MATERIALS,
  PRODUCTS_SET_YEARS,
  PRODUCTS_SET_REPORT_SCHEDULE_FINISHED_YEAR,
  PRODUCTS_SET_REPORT_SCHEDULE_CANCELED_YEAR,
  
  MATERIALS_SET_MATERIALS,
  MATERIALS_SET_SEARCH,
  MATERIALS_SET_SHOW_FILTER,
  MATERIALS_TOGGLE_SHOW_FILTER,
  MATERIALS_SET_MATERIAL,
  MATERIALS_SET_YEARS,
  MATERIALS_SET_REPORT_REGISTER_YEAR,
  MATERIALS_SET_REPORT_REMOVE_YEAR,

  COMBOS_SET_COMBOS,
  COMBOS_SET_SEARCH,
  COMBOS_SET_SHOW_FILTER,
  COMBOS_TOGGLE_SHOW_FILTER,
  COMBOS_SET_COMBO,
  COMBOS_SET_IMAGES,
  COMBOS_SET_SEARCH_IMAGES,
  COMBOS_SET_PRODUCTS,
  COMBOS_SET_SEARCH_PRODUCTS,

  CLIENTS_SET_CLIENTS,
  CLIENTS_SET_SEARCH,
  CLIENTS_SET_SHOW_FILTER,
  CLIENTS_TOGGLE_SHOW_FILTER,
  CLIENTS_SET_CLIENT,

  ADDRESS_SET_CITIES,
  ADDRESS_SET_COUNTRIES,

  AGENDA_SET_AGENDA,
  AGENDA_SET_SEARCH,
  AGENDA_SET_SHOW_FILTER,
  AGENDA_TOGGLE_SHOW_FILTER,
  AGENDA_SET_SCHEDULE,
  AGENDA_SET_MATERIALS,
  AGENDA_SET_PRODUCTS,
  AGENDA_SET_COMBOS
}