export const MODULE_NAME = 'clients';

//ACTIONS
export const ACTION_SET_CLIENTS = 'SET_CLIENTS';
export const ACTION_SET_SCHEDULES = 'SET_SCHEDULES';

//MUTATIONS
export const MUTATION_SET_CLIENTS = 'MUTATION_SET_CLIENTS'
export const MUTATION_SET_SEARCH = 'MUTATION_SET_SEARCH'
export const MUTATION_SET_SHOW_FILTER = 'MUTATION_SET_SHOW_FILTER'
export const MUTATION_TOGGLE_SHOW_FILTER = 'MUTATION_TOGGLE_SHOW_FILTER'
export const MUTATION_SET_CLIENT = 'MUTATION_SET_CLIENT'
export const MUTATION_SET_PAGE = 'MUTATION_SET_PAGE'
export const MUTATION_CLEAR_CLIENTS = 'MUTATION_CLEAR_CLIENTS'
export const MUTATION_SET_SCHEDULE_YEARS = 'MUTATION_SET_SCHEDULE_YEARS'
export const MUTATION_SET_REPORT_SCHEDULE_FINISHED_YEAR = 'MUTATION_SET_REPORT_SCHEDULE_FINISHED_YEAR'
export const MUTATION_SET_REPORT_SCHEDULE_CANCELED_YEAR = 'MUTATION_SET_REPORT_SCHEDULE_CANCELED_YEAR'
export const MUTATION_SET_SCHEDULES = 'MUTATION_SET_SCHEDULES'
export const MUTATION_SET_SCHEDULES_PAGE = 'MUTATION_SET_SCHEDULES_PAGE'

export default {
  MODULE_NAME,

  ACTION_SET_CLIENTS,
  ACTION_SET_SCHEDULES,

  MUTATION_SET_CLIENTS,
  MUTATION_SET_SEARCH,
  MUTATION_SET_SHOW_FILTER,
  MUTATION_TOGGLE_SHOW_FILTER,
  MUTATION_SET_CLIENT,
  MUTATION_SET_PAGE,
  MUTATION_CLEAR_CLIENTS,
  MUTATION_SET_SCHEDULE_YEARS,
  MUTATION_SET_REPORT_SCHEDULE_FINISHED_YEAR,
  MUTATION_SET_REPORT_SCHEDULE_CANCELED_YEAR,
  MUTATION_SET_SCHEDULES,
  MUTATION_SET_SCHEDULES_PAGE,
}