export const MODULE_NAME = 'address';

//MUTATIONS
export const MUTATION_SET_CITIES = 'MUTATION_SET_CITIES'
export const MUTATION_SET_COUNTRIES = 'MUTATION_SET_COUNTRIES'
export const MUTATION_CLEAR_CITIES = 'MUTATION_CLEAR_CITIES'
export const MUTATION_CLEAR_COUNTRIES = 'MUTATION_CLEAR_COUNTRIES'

export default {
  MODULE_NAME,
  MUTATION_SET_CITIES,
  MUTATION_SET_COUNTRIES,
  MUTATION_CLEAR_CITIES,
  MUTATION_CLEAR_COUNTRIES
}