export const MODULE_NAME = 'address';

//ACTIONS
export const ACTION_SET_CITIES = 'SET_CITIES';

//MUTATIONS
export const MUTATION_SET_CITIES = 'MUTATION_SET_CITIES'
export const MUTATION_SET_COUNTRIES = 'MUTATION_SET_COUNTRIES'
export const MUTATION_CLEAR_CITIES = 'MUTATION_CLEAR_CITIES'
export const MUTATION_SET_PAGE = 'MUTATION_SET_PAGE'
export const MUTATION_CLEAR_COUNTRIES = 'MUTATION_CLEAR_COUNTRIES'

export default {
  MODULE_NAME,

  ACTION_SET_CITIES,

  MUTATION_SET_CITIES,
  MUTATION_SET_COUNTRIES,
  MUTATION_CLEAR_CITIES,
  MUTATION_SET_PAGE,
  MUTATION_CLEAR_COUNTRIES
}