export const MODULE_NAME = 'app';

//ACTIONS
export const ACTION_LOADING = 'APP_LOADING';
export const ACTION_ADD_CANCEL_TOKEN = 'ACTION_ADD_CANCEL_TOKEN';
export const ACTION_CLEAR_PENDING_REQUESTS = 'ACTION_CLEAR_PENDING_REQUESTS';

//MUTATIONS
export const MUTATION_SET_LOADING = 'MUTATION_SET_LOADING';
export const MUTATION_SET_DRAWER = 'MUTATION_SET_DRAWER'
export const MUTATION_SET_IMAGE = 'MUTATION_SET_IMAGE'
export const MUTATION_SET_COLOR = 'MUTATION_SET_COLOR'
export const MUTATION_TOGGLE_DRAWER = 'MUTATION_TOGGLE_DRAWER'
export const MUTATION_SET_TOASTR = 'MUTATION_SET_TOASTR'
export const MUTATION_SET_PROGRESS_BAR = 'MUTATION_SET_PROGRESS_BAR'
export const MUTATION_TOGGLE_PROGRESS_BAR = 'MUTATION_TOGGLE_PROGRESS_BAR'
export const MUTATION_SET_NO_CONNECTION = 'MUTATION_SET_NO_CONNECTION';
export const MUTATION_SET_CANCEL_TOKENS = 'MUTATION_SET_CANCEL_TOKENS'
export const MUTATION_CLEAR_CANCEL_TOKENS = 'MUTATION_CLEAR_CANCEL_TOKENS'

export default {
  MODULE_NAME,
  
  ACTION_LOADING,
  ACTION_ADD_CANCEL_TOKEN,
  ACTION_CLEAR_PENDING_REQUESTS,

  MUTATION_SET_LOADING,
  MUTATION_SET_DRAWER,
  MUTATION_SET_IMAGE,
  MUTATION_SET_COLOR,
  MUTATION_TOGGLE_DRAWER,
  MUTATION_SET_TOASTR,
  MUTATION_SET_PROGRESS_BAR,
  MUTATION_TOGGLE_PROGRESS_BAR,
  MUTATION_SET_NO_CONNECTION,
  MUTATION_SET_CANCEL_TOKENS,
  MUTATION_CLEAR_CANCEL_TOKENS
}