export const MODULE_NAME = 'app';

//ACTIONS
export const ACTION_LOADING = 'APP_LOADING';

//MUTATIONS
export const MUTATION_SET_LOADING = 'MUTATION_SET_LOADING';
export const MUTATION_SET_DRAWER = 'MUTATION_SET_DRAWER'
export const MUTATION_SET_IMAGE = 'MUTATION_SET_IMAGE'
export const MUTATION_SET_COLOR = 'MUTATION_SET_COLOR'
export const MUTATION_TOGGLE_DRAWER = 'MUTATION_TOGGLE_DRAWER'
export const MUTATION_SET_TOASTR = 'MUTATION_SET_TOASTR'
export const MUTATION_SET_PROGRESS_BAR = 'MUTATION_SET_PROGRESS_BAR'
export const MUTATION_TOGGLE_PROGRESS_BAR = 'MUTATION_TOGGLE_PROGRESS_BAR'

export default {
    MODULE_NAME,
    ACTION_LOADING,
    MUTATION_SET_LOADING,
    MUTATION_SET_DRAWER,
    MUTATION_SET_IMAGE,
    MUTATION_SET_COLOR,
    MUTATION_TOGGLE_DRAWER,
    MUTATION_SET_TOASTR,
    MUTATION_SET_PROGRESS_BAR,
    MUTATION_TOGGLE_PROGRESS_BAR
}