export const MODULE_NAME = 'combos';

//ACTIONS
export const ACTION_SET_COMBOS = 'SET_COMBOS';
export const ACTION_SET_ON_SALE_COMBOS = 'ACTION_SET_ON_SALE_COMBOS';
export const ACTION_SET_SCHEDULES = 'SET_SCHEDULES';
export const ACTION_SET_SALES = 'SET_SALES';

//MUTATIONS
export const MUTATION_SET_COMBOS = 'MUTATION_SET_COMBOS'
export const MUTATION_SET_ON_SALE_COMBOS = 'MUTATION_SET_ON_SALE_COMBOS'
export const MUTATION_SET_SEARCH = 'MUTATION_SET_SEARCH'
export const MUTATION_SET_SHOW_FILTER = 'MUTATION_SET_SHOW_FILTER'
export const MUTATION_TOGGLE_SHOW_FILTER = 'MUTATION_TOGGLE_SHOW_FILTER'
export const MUTATION_SET_COMBO = 'MUTATION_SET_COMBO'
export const MUTATION_SET_IMAGES = 'MUTATION_SET_IMAGES'
export const MUTATION_SET_SEARCH_IMAGES = 'MUTATION_SET_SEARCH_IMAGES'
export const MUTATION_SET_PRODUCTS = 'MUTATION_SET_PRODUCTS'
export const MUTATION_SET_SEARCH_PRODUCTS = 'MUTATION_SET_SEARCH_PRODUCTS'
export const MUTATION_SET_PAGE = 'MUTATION_SET_PAGE'
export const MUTATION_SET_ON_SALE_PAGE = 'MUTATION_SET_ON_SALE_PAGE'
export const MUTATION_CLEAR_COMBOS = 'MUTATION_CLEAR_COMBOS'
export const MUTATION_SET_SCHEDULE_YEARS = 'MUTATION_SET_SCHEDULE_YEARS'
export const MUTATION_SET_REPORT_SCHEDULE_FINISHED_YEAR = 'MUTATION_SET_REPORT_SCHEDULE_FINISHED_YEAR'
export const MUTATION_SET_REPORT_SCHEDULE_CANCELED_YEAR = 'MUTATION_SET_REPORT_SCHEDULE_CANCELED_YEAR'
export const MUTATION_SET_SCHEDULES = 'MUTATION_SET_SCHEDULES'
export const MUTATION_SET_SCHEDULES_PAGE = 'MUTATION_SET_SCHEDULES_PAGE'
export const MUTATION_SET_SALES = 'MUTATION_SET_SALES'
export const MUTATION_SET_SALES_PAGE = 'MUTATION_SET_SALES_PAGE'

export default {
  MODULE_NAME,

  ACTION_SET_COMBOS,
  ACTION_SET_ON_SALE_COMBOS,
  ACTION_SET_SCHEDULES,
  ACTION_SET_SALES,

  MUTATION_SET_COMBOS,
  MUTATION_SET_ON_SALE_COMBOS,
  MUTATION_SET_SEARCH,
  MUTATION_SET_SHOW_FILTER,
  MUTATION_TOGGLE_SHOW_FILTER,
  MUTATION_SET_COMBO,
  MUTATION_SET_IMAGES,
  MUTATION_SET_SEARCH_IMAGES,
  MUTATION_SET_PRODUCTS,
  MUTATION_SET_SEARCH_PRODUCTS,
  MUTATION_SET_PAGE,
  MUTATION_SET_ON_SALE_PAGE,
  MUTATION_CLEAR_COMBOS,
  MUTATION_SET_SCHEDULE_YEARS,
  MUTATION_SET_REPORT_SCHEDULE_FINISHED_YEAR,
  MUTATION_SET_REPORT_SCHEDULE_CANCELED_YEAR,
  MUTATION_SET_SCHEDULES,
  MUTATION_SET_SCHEDULES_PAGE,
  MUTATION_SET_SALES,
  MUTATION_SET_SALES_PAGE
}