export const MODULE_NAME = 'combos';

//ACTIONS
export const ACTION_SET_COMBOS = 'SET_COMBOS';

//MUTATIONS
export const MUTATION_SET_COMBOS = 'MUTATION_SET_COMBOS'
export const MUTATION_SET_SEARCH = 'MUTATION_SET_SEARCH'
export const MUTATION_SET_SHOW_FILTER = 'MUTATION_SET_SHOW_FILTER'
export const MUTATION_TOGGLE_SHOW_FILTER = 'MUTATION_TOGGLE_SHOW_FILTER'
export const MUTATION_SET_COMBO = 'MUTATION_SET_COMBO'
export const MUTATION_SET_IMAGES = 'MUTATION_SET_IMAGES'
export const MUTATION_SET_SEARCH_IMAGES = 'MUTATION_SET_SEARCH_IMAGES'
export const MUTATION_SET_PRODUCTS = 'MUTATION_SET_PRODUCTS'
export const MUTATION_SET_SEARCH_PRODUCTS = 'MUTATION_SET_SEARCH_PRODUCTS'
export const MUTATION_SET_PAGE = 'MUTATION_SET_PAGE'
export const MUTATION_CLEAR_COMBOS = 'MUTATION_CLEAR_COMBOS'

export default {
    MODULE_NAME,
    ACTION_SET_COMBOS,
    MUTATION_SET_COMBOS,
    MUTATION_SET_SEARCH,
    MUTATION_SET_SHOW_FILTER,
    MUTATION_TOGGLE_SHOW_FILTER,
    MUTATION_SET_COMBO,
    MUTATION_SET_IMAGES,
    MUTATION_SET_SEARCH_IMAGES,
    MUTATION_SET_PRODUCTS,
    MUTATION_SET_SEARCH_PRODUCTS,
    MUTATION_SET_PAGE,
    MUTATION_CLEAR_COMBOS
}