export const MODULE_NAME = 'products';

//ACTIONS
export const ACTION_SET_PRODUCTS = 'SET_PRODUCTS';

//MUTATIONS
export const MUTATION_SET_PRODUCTS = 'MUTATION_SET_PRODUCTS'
export const MUTATION_SET_SEARCH = 'MUTATION_SET_SEARCH'
export const MUTATION_SET_SHOW_FILTER = 'MUTATION_SET_SHOW_FILTER'
export const MUTATION_TOGGLE_SHOW_FILTER = 'MUTATION_TOGGLE_SHOW_FILTER'
export const MUTATION_SET_PRODUCT = 'MUTATION_SET_PRODUCT'
export const MUTATION_SET_IMAGES = 'MUTATION_SET_IMAGES'
export const MUTATION_SET_SEARCH_IMAGES = 'MUTATION_SET_SEARCH_IMAGES'
export const MUTATION_SET_COMBOS = 'MUTATION_SET_COMBOS'
export const MUTATION_SET_MATERIALS = 'MUTATION_SET_MATERIALS'
export const MUTATION_SET_SEARCH_MATERIALS = 'MUTATION_SET_SEARCH_MATERIALS'

export default {
    MODULE_NAME,
    ACTION_SET_PRODUCTS,
    MUTATION_SET_PRODUCTS,
    MUTATION_SET_SEARCH,
    MUTATION_SET_SHOW_FILTER,
    MUTATION_TOGGLE_SHOW_FILTER,
    MUTATION_SET_PRODUCT,
    MUTATION_SET_IMAGES,
    MUTATION_SET_SEARCH_IMAGES,
    MUTATION_SET_COMBOS,
    MUTATION_SET_MATERIALS,
    MUTATION_SET_SEARCH_MATERIALS
}