export default {
  products: [],
  onSaleProducts: [],
  search: false,
  showFilter: false,
  product: {},
  images: [],
  searchImages: false,
  combos: [],
  materials: [],
  searchMaterials: false,
  page: {},
  onSalePage: {},
  scheduleYears: [],
  reportScheduleFinishedYear: {
    months: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  reportScheduleCanceledYear: {
    months: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  schedules: [],
  schedulesPage: {},
  sales: [],
  salesPage: {},
}
