export const MODULE_NAME = 'agenda';

//ACTIONS
export const ACTION_SET_AGENDA = 'SET_AGENDA';

//MUTATIONS
export const MUTATION_SET_AGENDA = 'MUTATION_SET_AGENDA'
export const MUTATION_SET_SEARCH = 'MUTATION_SET_SEARCH'
export const MUTATION_SET_SHOW_FILTER = 'MUTATION_SET_SHOW_FILTER'
export const MUTATION_TOGGLE_SHOW_FILTER = 'MUTATION_TOGGLE_SHOW_FILTER'
export const MUTATION_SET_PAGE = 'MUTATION_SET_PAGE'
export const MUTATION_CLEAR_AGENDA = 'MUTATION_CLEAR_AGENDA'
export const MUTATION_SET_SCHEDULE = 'MUTATION_SET_SCHEDULE'
export const MUTATION_SET_MATERIALS = 'MUTATION_SET_MATERIALS'
export const MUTATION_SET_PRODUCTS = 'MUTATION_SET_PRODUCTS'
export const MUTATION_SET_COMBOS = 'MUTATION_SET_COMBOS'

export default {
  MODULE_NAME,
  ACTION_SET_AGENDA,
  MUTATION_SET_AGENDA,
  MUTATION_SET_SEARCH,
  MUTATION_SET_SHOW_FILTER,
  MUTATION_TOGGLE_SHOW_FILTER,
  MUTATION_SET_PAGE,
  MUTATION_CLEAR_AGENDA,
  MUTATION_SET_SCHEDULE,
  MUTATION_SET_MATERIALS,
  MUTATION_SET_PRODUCTS,
  MUTATION_SET_COMBOS
}